### PR TITLE
Properly parse bower.json

### PR DESCRIPTION
**Pull request by matthewp**
Some work is needed to parse the `bower.json` into a format acceptable by jspm so that all dependencies are retrieved. [Example bower.json](https://github.com/twbs/bootstrap/blob/master/bower.json). Open questions:
1. What can we do about packages with multiple `main`s?
2. Is it ok to use the same semver logic as the npm endpoint?
   
   cc @guybedford

### CODE REVIEW

**Comment by guybedford** [comment]
@matthewp to update you on a timeline here, I'm still trying to get SystemJS out the door, which is the priority for this next week. After that I can be more flexible for helping out with improvements this side, but will have to see how the priorities work out then. If there is anything that you need that is pressing, do feel free to ask though.

**Comment by matthewp** [comment]
@guybedford No problem, nothing urgent is needed anyways.  I've updated master with the changes needed for this issue, so please update the server when you can.

**Comment by guybedford** [comment]
@matthewp sure will do - if you can publish to npm it would make it easier.

**Comment by matthewp** [comment]
Sorry, forgot to do that. Published it to version 0.0.2

**Comment by guybedford** [comment]
I've updated the server now to 0.0.2.

**Pull request merged**
